クラス図の作成
A20-1409komaki/java_sample pull request #3
Opened 2022-05-10 09:13 UTC by A20-1409komaki

# 概要
クラス図を作成しました。よろしくお願いします。

2022-05-12 07:30 UTC, a191409 commented on docs/classzu.puml
> +    + Confirmation()
メソッドは全部頭文字、小文字で統一したほうが、後々紛らわしくなくなるので、統一したほうがいいかな。
「このメソッドは小文字だっけ？大文字だっけ？」ってなるので。

2022-05-12 07:31 UTC, a191409 commented on docs/classzu.puml
> +
created_atがあるのであれば、updated_atも全部に付け加えたほうがいいかな。

2022-05-12 07:34 UTC, a191409 commented on docs/classzu.puml
> +    Int category_id
ここでいうcategory_idは外部キーをイメージしてるかな？
伝え忘れていたんだけど、外部キーは一番下に書いて、外部キーなのか明確にしてほしいです！

2022-05-12 07:36 UTC, a191409 commented on docs/classzu.puml
> +class Category{
categoryもtaskも誰が投稿したか不明だけど、それって問題ないかな？

2022-05-12 07:39 UTC, a191409 commented on docs/classzu.puml
> +    + Confirmation()
あと、confirmationって何をする機能だ...?
taskの方にもあるけど。閲覧機能のこと？

2022-05-12 07:39 UTC, a191409 commented on docs/classzu.puml
> +    + notice()
このnoticeってどの機能のことを指してる？

2022-05-12 07:41 UTC, a191409 requested changes
一通り見て、コメント残したので、確認して修正してまた上げ直してみてね！

2022-05-12 08:02 UTC, a191409 requested changes
てすと

2022-05-12 08:04 UTC, a191409 requested changes
てすと2

2022-05-12 09:00 UTC, A20-1409komaki commented on docs/classzu.puml
> +    + Confirmation()
全て小文字に統一しました。

2022-05-12 09:07 UTC, A20-1409komaki commented on docs/classzu.puml
> +
付け加えました。

2022-05-12 09:12 UTC, A20-1409komaki commented on docs/classzu.puml
> +    Int category_id
わかりました！Foreignkeyと書き加えました。

2022-05-12 09:12 UTC, A20-1409komaki commented on docs/classzu.puml
> +class Category{
管理するときに困りそうです！ユーザのIDを書き加えました。

2022-05-12 09:15 UTC, A20-1409komaki commented on docs/classzu.puml
> +    + Confirmation()
多分閲覧機能です！あまり覚えてないですが「閲覧　英語」でググったら出てきたんだと思います・・・。
readingにしておきます。

2022-05-12 09:16 UTC, A20-1409komaki commented on docs/classzu.puml
> +    + notice()
通知機能です。announceにしました。

2022-05-15 14:36 UTC, a191409 approved these changes
大丈夫そうなので、mergeして問題なさそうです！

2022-05-17 02:08 UTC, merged